### ISSUE TITLE
Using context functionality of kubectl

### ISSUE THREAD

**Issue by tkelkermans** [nutanix/kubectl-karbon#32]
Hi,

Would it be possible to use the context functionality of kubectl with this plugin ?
For example :

1. Use kubectl Karbon login --server prism-central-address -u
2. Automatically creates context so that we can switch between the different NKE clusters that have been deployed
`kubectl config use-context nke-01`
`kubectl config use-context nke-02`

I think it would help instead of overwriting or changing the kubeconfig file every time ?

Thanks

**Comment by omBratteng** [comment]
This would be very useful. We have 6 clusters, and sometimes we need to work with multiple at the same time
