### ISSUE TITLE
Allows to generate kubeconfig file for multiple / all NKE cluster for a given PC

### ISSUE THREAD

**Issue by fabricekrebs** [nutanix/kubectl-karbon#45]
When managing multiple NKE clusters with a same PC, it would be nice to be able to select multiple / all clusters to generate kubeconfig file.

Then all selected NKE cluster would have a context defined in the the output kubeconfig file

**Comment by tuxtof** [comment]
duplicate #32 
actually the `--kubie` mode is a good/better ?? alternative to the context approach

**Comment by fabricekrebs** [comment]
I don't think it's a duplicate. Here the request is to avoid to run 6 times the command if we've 6 NKE to manage. Then running once the command, and being to be able to select the 6 clusters, would be much faster

**Comment by tuxtof** [comment]
the feature request is clear
i mark it as duplicate because it is part of the PRD we have made for #32 
WIP
